### ISSUE TITLE
Away day: inconsistency between bluebird instances

### ISSUE THREAD

**Issue by evelinag** [alan-turing-institute/bluebird#74]
I'm communicating with the three Bluebird instances running on our Azure VM and I'm getting incosistencies. The Bluebirds are operating on ports 5000, 5001 and 5002.

I created a single aircraft and `pos?acid=all` command gives me:

- port 5000 : "No aircraft in simulation"
- port 5001 : Returns the correct aircraft information
- port 5002 : Also returns the aircraft information

Port 5000 doesn't seem to be pointing to the same Bluesky instance if that's possible?

**Comment by evelinag** [comment]
On second thought, it seems that Bluebird crashes silently and stops responding properly. Current state is that two of the three Bluebird instances (running on Azure on ports 5000 and 5001) are responding "No aircraft in simulation", when the third Bluebird instance responds correctly with a list of planes.

**Comment by rkm** [comment]
Closing this - We can investigate if we plan to run that demo again.
