### ISSUE TITLE
New endpoint to upload geoJSON sector definition

### ISSUE THREAD

**Issue by tallamjr** [alan-turing-institute/bluebird#77]
This should then be agnostic to which simulator it then passes off to

**Comment by tallamjr** [comment]
Linked to https://github.com/alan-turing-institute/nats/issues/103

**Comment by rkm** [comment]
I've created a new branch for this feature https://github.com/alan-turing-institute/bluebird/tree/feature/77-geoJSON-sector-upload.

**Comment by rkm** [comment]
Completed in `develop` 🚀
